"""
build_db_data.py
================
One-time data build script.
Merges:
  - data/accommodations.geojson   (50 buildings, OSM + generated footprints)
  - data/amenities_cache.json     (280 pre-fetched amenity polygons per building)
  - data/Manchester All Data.json (rich upstream data: price, description, images)

Outputs:
  - data/manchester_buildings.js  → JS variable `manchesterBuildingsData`
  - data/manchester_amenities.js  → JS variable `manchesterAmenitiesData`
"""
import json
import os

DATA_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'data')

# Maps amenities_cache category keys → user-facing display names
CATEGORY_MAP = {
    'restaurants':       'Restaurant',
    'cafes':             'Cafe',
    'bars':              'Bar',
    'nightclubs':        'Nightclub',
    'sports_centres':    'Sports Centre',
    'convenience_stores':'Convenience Store',
    'libraries':         'Library',
    'metro_stations':    'Metro Station',
    'bus_stops':         'Bus Stop',
    'parks':             'Park',
    'places_of_worship': 'Church',
    'supermarkets':      'Supermarket',
    'pharmacies':        'Pharmacy',
    'gyms':              'Gym',
    'universities':      'University',
}

def load_json(path):
    print(f"  Loading {os.path.basename(path)}...")
    with open(path, 'r', encoding='utf-8') as f:
        return json.load(f)

def write_js(path, var_name, data):
    with open(path, 'w', encoding='utf-8') as f:
        f.write('// Auto-generated by build_db_data.py — DO NOT EDIT MANUALLY\n')
        f.write(f'const {var_name} = ')
        f.write(json.dumps(data, ensure_ascii=False, separators=(',', ':')))
        f.write(';\n')
    size_kb = os.path.getsize(path) / 1024
    print(f"  ✅ Written {os.path.basename(path)}  ({size_kb:.1f} KB)")

def calc_height(props):
    """Return a sane building height from available data."""
    levels = props.get('building_levels', '')
    if levels:
        try:
            return max(8.0, float(levels) * 3.5)
        except (ValueError, TypeError):
            pass
    h = props.get('height', 0)
    if h and h > 2:
        return float(h)
    return 30.0  # sensible default for student accommodation

def build():
    print("\n📦 Building Manchester 3D Map data files...")

    # ── Load all sources ──────────────────────────────────────────────────────
    geojson       = load_json(os.path.join(DATA_DIR, 'accommodations.geojson'))
    amenities_raw = load_json(os.path.join(DATA_DIR, 'amenities_cache.json'))
    manchester    = load_json(os.path.join(DATA_DIR, 'Manchester All Data.json'))

    # Build id → house lookup from Manchester All Data
    houses_by_id = {}
    for house in manchester.get('data', {}).get('houses', []):
        hid = str(house.get('house_id', '') or '')
        if hid:
            houses_by_id[hid] = house
    print(f"  Loaded {len(houses_by_id)} houses from Manchester All Data.json")

    # ─────────────────────────────────────────────────────────────────────────
    # 1. manchester_buildings.js
    # ─────────────────────────────────────────────────────────────────────────
    enhanced_features = []
    for feat in geojson['features']:
        props = dict(feat['properties'])
        hid   = str(props.get('id', ''))
        house = houses_by_id.get(hid, {})

        # Enrich with upstream detail
        if house:
            # Truncate description to 400 chars for JS weight
            about = (house.get('about', '') or '').strip()
            props['about']       = about[:400]
            props['house_url']   = house.get('house_url', '') or ''
            props['bed_num']     = int(house.get('bed_num') or 0)
            props['total_floor'] = int(house.get('total_floor') or 0)
            imgs = house.get('media_updated_images') or []
            props['image_url']   = imgs[0] if imgs else ''

        # Normalise height
        props['height']      = calc_height(props)
        props['base_height'] = 0

        enhanced_features.append({
            'type':       'Feature',
            'id':         feat['id'],
            'geometry':   feat['geometry'],
            'properties': props,
        })

    buildings_data = {
        'type':     'FeatureCollection',
        'features': enhanced_features,
    }
    write_js(
        os.path.join(DATA_DIR, 'manchester_buildings.js'),
        'manchesterBuildingsData',
        buildings_data,
    )
    print(f"  → {len(enhanced_features)} accommodation features")

    # ─────────────────────────────────────────────────────────────────────────
    # 2. manchester_amenities.js
    # ─────────────────────────────────────────────────────────────────────────
    amenities_out = {}
    total_polys   = 0

    for acc_id, acc_data in amenities_raw.get('accommodations', {}).items():
        features = []
        summary  = {}

        for raw_key, item_list in acc_data.get('amenities', {}).items():
            if not isinstance(item_list, list):
                continue
            display_cat = CATEGORY_MAP.get(raw_key, raw_key.replace('_', ' ').title())

            for item in item_list:
                geom = item.get('geometry')
                if not geom or geom.get('type') != 'Polygon':
                    continue
                coords = geom.get('coordinates', [])
                if not coords or len(coords[0]) < 3:
                    continue

                item_props = item.get('properties', {})
                height = float(item_props.get('height', 12) or 12)

                # Realistic minimums by category
                if display_cat == 'Park':
                    height = 1.5
                elif display_cat in ('Bus Stop',):
                    height = 3.5
                elif height < 4:
                    height = 7.0

                features.append({
                    'type': 'Feature',
                    'properties': {
                        'name':        item.get('name', display_cat),
                        'category':    display_cat,
                        'height':      height,
                        'base_height': 0,
                        'distance_m':  item.get('distance_m', 0),
                        'osm_id':      item_props.get('osm_id')
                    },
                    'geometry': geom,
                })
                summary[display_cat] = summary.get(display_cat, 0) + 1

        amenities_out[acc_id] = {
            'name':     acc_data.get('name', ''),
            'features': features,
            'summary':  summary,
        }
        total_polys += len(features)

    write_js(
        os.path.join(DATA_DIR, 'manchester_amenities.js'),
        'manchesterAmenitiesData',
        amenities_out,
    )
    print(f"  → {len(amenities_out)} accommodation entries, {total_polys} amenity polygons")
    print("\n🎉 Done! Both JS data files are ready.\n")

if __name__ == '__main__':
    build()
